In [1]:
import numpy as np

In [22]:
tetris_matrix = np.zeros(( 4, 6 ))
current_state = 0
npoints = 0

tetris_matrix[0,1] = 1
print(tetris_matrix)


[[0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [24]:
def fall_piece(col):
    for c in range(tetris_matrix.shape[1]):
        pass

fall_piece(0)